# This files configures releases for this repository.
archives:
- format: binary
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'

signs:
  - artifacts: checksum
    cmd: sh
    args:
      - -c
      - |
        if [ -n "${GPG_FINGERPRINT}" ]; then
          gpg --batch --local-user "${GPG_FINGERPRINT}" --output "${signature}" --detach-sign "${artifact}"
        else
          echo "Skipping signing: GPG_FINGERPRINT not set" >&2
          exit 0
        fi

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
