# This files configures releases for this repository.
archives:
- format: binary
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'

release:
  draft: true

# Uncomment to enable GPG signing (requires GPG_FINGERPRINT env var):
# signs:
#   - artifacts: checksum
#     cmd: gpg
#     args:
#       - --batch
#       - --local-user
#       - "{{ .Env.GPG_FINGERPRINT }}"
#       - --output
#       - "${signature}"
#       - --detach-sign
#       - "${artifact}"

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
